[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
addopts = "-v --tb=short -q"

[tool.coverage.run]
source = ["azext_prototype"]

[tool.coverage.report]
show_missing = true
skip_empty = true
